### ISSUE TITLE
  [Doctrine\ODM\MongoDB\Mapping\MappingException] Type object already exists

### ISSUE THREAD

**Issue by fabricek** [vespolina/vespolina-sandbox#110]
When doing "php app / console cache: clear" in a fresh install of the V sandbox it gets an error :
[Doctrine\ODM\MongoDB\Mapping\MappingException]   Type object already exists.
The error message is too simple, ad i can't figure it out. How can we solve that  ?

**Comment by iampersistent** [comment]
I need to dig into this further to find out what the problem is. Thanks for info.

**Comment by fabricek** [comment]
I've solved it. I just try to learn howw to do a pull request.

**Comment by fabricek** [comment]
I'm new on git hub.

**Comment by iampersistent** [comment]
Let me know if you need some help getting around.

**Comment by fabricek** [comment]
thanks

2014-04-07 8:51 GMT+02:00 Richard Shank notifications@github.com:

> Let me know if you need some help getting around.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/vespolina/vespolina-sandbox/issues/110#issuecomment-39700576
> .

## 

Cordialement,

Fabrice Kuissu

**Comment by fabricek** [comment]
Thanks for your help.
I don't know how to re-open my v/media thread you've closed. May i create a new issue number ?

## I m asking you before create a new one

## This is my comment for v/media :

## Yes you've put it in v/core and I've viewed that. But for some reasons it is not download from composer and so not install. I've tried to force the require in core/composer.json but result in bad install by composer. So the best way for me was to put it in v-sandbox/composer.json to have the media installed and the sandbox run. Actually the fresch install of the sandbox didn't install v/media. Again i'll put a pr when i'll learn how to do.

**Comment by fabricek** [comment]
sorry for the typo i've putted some "-" in the text i didn't know

**Comment by iampersistent** [comment]
if you haven't already, try `composer update vespolina/core` and see if that helps. @inspiran reported that it helped him.

**Comment by fabricek** [comment]
Maybe but i don't want to try with another fresh install. I think that
modify the v/sandbox composer.json is the best way. If not the fresh
install fails !  Asking you afterall and making a probably composer update
vespolina/core from @inspiran https://github.com/inspiran is not a great
solution. With mine the sandbox will run out of the box so i'll submit you
a pr when i'll understand how it works. Solution was just to add
"vespolina/media": "*"  in v/sandbox composer.json since you've deleted the
Asset in v/core

2014-04-07 9:21 GMT+02:00 Richard Shank notifications@github.com:

> if you haven't already, try composer update vespolina/core and see if
> that helps. @inspiran https://github.com/inspiran reported that it
> helped him.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/vespolina/vespolina-sandbox/issues/110#issuecomment-39702116
> .

## 

Cordialement,

Fabrice Kuissu
