### ISSUE TITLE
Vespolina: store-setup setValue () error

### ISSUE THREAD

**Issue by fabricek** [vespolina/vespolina-sandbox#118]
An error occurs when doing a fresh install and after php app / console Vespolina: store-setup.

---

PHP Fatal error: Call to undefined method Vespolina \ Entity \ Product \ Option :: setValue  () in Vespolina-sandbox\ vendor \ Vespolina \ commerce \ lib \ Vespolina \ Product \ Manager \ ProductManager.php on line 161
It is solved here https://github.com/vespolina/commerce/pull/24/files

**Comment by iampersistent** [comment]
That has been merged now. Thanks
