### ISSUE TITLE
Vespolina setup error

### ISSUE THREAD

**Issue by fabricek** [vespolina/vespolina-sandbox#119]
An error occurs when doing a fresh install. We have a blank page and the apache log show :

---

PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not resolve request to a store' in C:\wamp\www\vespolina-sandbox_or\vendor\vespolina\store-bundle\Vespolina\StoreBundle\Resolver\SingleStoreResolver.php:33\nStack trace:\n#0 
I don't know how to solve it for the moment.

**Comment by cordoval** [comment]
maybe you don't have the store loaded on db, if you are in a rush i recommend you other solutions for ecommerce, but if you have time for FOSS, then focus on vespolina/workflow

**Comment by fabricek** [comment]
Can't you solve the problem ? cause if nobody can install the sandbox no so many developpers can contribute. I had contribute to the project a bit and i want to continue. But how to, if i can't install the sandbox ?

**Comment by iampersistent** [comment]
@inspiran was behind a lot of this specific code, maybe he has a quick solution.

**Comment by fabricek** [comment]
Thanks i'm working on that.

2014-06-21 18:49 GMT+02:00 Richard Shank notifications@github.com:

> @inspiran https://github.com/inspiran was behind a lot of this specific
> code, maybe he has a quick solution.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vespolina/vespolina-sandbox/issues/119#issuecomment-46758619
> .

## 

Cordialement,

Fabrice Kuissu

**Comment by fabricek** [comment]
I don't know how to solve it but this is a workaround.
- The problem appears only when working in a production environment.
- Working with app_dev.php (development environment) is fine.
  It's because when doing a fresh install, the "php app / console Vespolina: store-setup" command only create a vespolina_dev mongodb database.

The workaround : copy vespolina_dev  (the mongodb database) and name it as vespolina_prod so you will have the two databases. However that's not solve the setup. Wait the team solve it.

This workaround solve the error but an other problem still remain in production environment with css.

**Comment by wjzijderveld** [comment]
Have you tried running the store-setup command as production?

vespolina:store-setup -e production

**Comment by fabricek** [comment]
Yes that's the rigth way and solve the problem.
And more for the css problem doing : php app/console assets:install --env=prod solve it too.
So after install we must do :
php app/console vespolina:store-setup --env=prod
php app/console assets:install --env=dev
Thanks
