### ISSUE TITLE
Separating bundles

### ISSUE THREAD

**Issue by stof** [vespolina/vespolina-sandbox#15]
The project is meant to be `built on interchangeable bundles that can be used independently of Vespolina` according to the wiki. But the current way to go makes it impossible to reuse the bundles easily as vespolina/vespolina is a project and all bundles are into the project. Thus, vendor/bundles is meant to contain vendor bundles so putting app-specific bundles (which is what Vespolina bundles are currently) into it does not make sense.
Thus separating bundles in their own repo will make it easier to follow their development as someone could watch a bundle without having all changes made in other bundles and you don't need to merge changes done in other bundles, avoiding merge commits.

**Comment by iampersistent** [comment]
I agree with this and we will work toward making them more independent.  Later this week, I will be making some updates to the MonetaryBundle and moving into its own repo. Right now, that is the only bundle that can be moved out, but we will get there.

Was there anything in particular you are needing immediately?

**Comment by inspiran** [comment]
I do agree on the split.  The reason why we didn't do it yet is to speed up the development process and just the simple fact that some bundles are pretty much tight to each other for now.  (eg. product bundle will need the pricing bundle).  Besides the monetary bundle i think the next bundle which we can split is the work flow bundle.

**Comment by stof** [comment]
I have no particular need immediately. I opened this issue after a discussion with someone else on IRC during which the Vespolina project was referenced.

**Comment by merk** [comment]
Why will the product bundle need the pricing bundle? You should be able to create a catalog of products without pricing information.

**Comment by inspiran** [comment]
Actually we've discussed whether or not a product should always have a price.  We did not find any decent use case where the price was not needed. Note that pricing does not only include pricing info related to the selling price but also can include company-internal values such as profit-margin, production cost, ..
Could you give an example where pricing is irrelevant?

**Comment by stof** [comment]
@inspiran Then the PricingBundle has logically a dependency to the ProductBundle (as pricing are for a product) but I'm quite sure the product bundle does not need the dependency.

**Comment by merk** [comment]
Over the last year, we've had many customers come to us asking for a shopping cart "without the cart" -- all they want is a product catalog online, they dont want the store or pricing components.

As Stof said - the dependency is one way: the PricingBundle requires ProductBundle, but the ProductBundle shouldnt require Pricing. The more decoupled each of the bundles of this project are, the more likely I'll be able to contribute significant development time to specific bundles that solve issues for my projects. I wont need your entire solution for most of my projects, but i want to be able to pick and choose :)

**Comment by merk** [comment]
It would also be very cool, if the PricingBundle supported any kind of entity to be priced, not just a product. There doesnt need to be a dependency on a product, what about pricing a service?

**Comment by iampersistent** [comment]
@merk, I agree 100% If there is a need to have interaction between bundles, it should only be through services, interfaces and configuration. 

Perhaps, what needs to happen with product to look at it as just a widget. In the physical world, we don't have to attach a price to an widget. It could be prototype or a From a very over simplified perspective, Its only when its put out for sale that a price is relevant. So perhaps we need a "for sale" object that references a product type and price that can be put on "a shelf" to be sold.

**Comment by merk** [comment]
Thats sounds like it could be a good solution, you end up with a 'for sale' object that can reference any kind of object that you might want to sell, be it ad space, a product, a recurring subscription - it wont matter.

I hope to dive in the deep end in the next week. I've got a big project starting in the next 4-6 weeks that will need most of the functionality provided by (at least, promised by) vespolina, so I'll need to wrap my head around everything. 

I'll be so much nicer to deal with if bundles can be swapped out, or used independently.

**Comment by inspiran** [comment]
@merk Normally the pricing bundle should be able to price all kinds of entities.  For now we'll be supporting pricing of products, the shopping cart and the subsequent sales document (OrderBundle). 
The only requirement (and hence dependence) is that an entity that needs to be priced implements the PriceableEntityInterface.   Note that ProductBundle depends on PricingBundle, not the other way around.  

But i like the idea of decoupling the price from the product using a ForSale kind of object.  Using this approach you could actually make multi-stores easier to manage.  Different products can have different prices in different stores.  So you would end up with a product having multiple pricing views linked to different stores (or sales channels).  Actually you could do the same for different kinds of data.  

What I've currently in mind based on the comments you guys made:

A Product  holds multiple ProductView instances.  A ProductPricingView is a subclass of ProductView.  Another subclass could be for example ProductStockView (what is where in stock ).
Based on contextual information (what is the current store, what is the current product category, who is viewing this product) we determine which ProductView instances of a product should be loaded.

I know use cases where the product description depends on who is viewing the product (normal vs premium customers).  So in this case I could imagine that we could even have multiple ProductDescriptionView instances for a given product.

In fact with this approach we have a pretty extensible way of managing custom product data in different environments.
So in Merk's case he would not have any ProductPricingView instances and hence no pricing will be displayed.

**Comment by merk** [comment]
PricableEntityInterface is good - that approach allows any bundle to subscribe/allow its own entities to be priced. I've got no issues with such an approach.

I also do not agree with your assessment that the ProductBundle will depend on PricingBundle. To me this proves the architecture is flawed: The ProductBundle should be provide functionality related to Products, and work independently of the availability of pricing services. These functions do not depend on pricing. The PricingBundle, however, depends on the presence of objects that want to have a price - in this case, coming from ProductBundle.

I dont have much feedback about the direction you're thinking about, but my only comment is that Pricing is not a responsibility of a View, and as such the classes shouldn't be named that way. Otherwise it seems like it could be a potential solution.

**Comment by stof** [comment]
@merk If the product is priced directly, it would depend of ProductBundle because of the interface (which would be in PricingBundle). So to make them decoupled, the ProductPricingView approch is the good one IMO. In this case there should be a third bundle (ProductPricingBundle ?) containing the ProductPricingView with a dependency to both ProductBundle and PricingBundle (which is acceptable as this bundle is about tying the other 2 together).

PricingBundle has no dependency to ProductBundle as soon as it accept any object implementing the interface (it is useless if you have no implementation of the interface but it work and the implementation can be another one)

**Comment by merk** [comment]
Yeah, I realise that if it is going to be priced directly there would need to be a relationship. However, there are solutions to that problem by not storing the pricing directly in the product, I envisage something along the lines of (adapted to use the MonetaryBundle, of course)

``` php
<?php

$product = new ProductBundle\Entity\Product();
$pricing = new PricingBundle\Entity\Price();
$pricing->setPrice(10.00);
$this->container->get('vespolina.pricing')->addPrice($product, $price);

```

Or, make the developer implement a Product entity which can implement the Pricing interface itself.

The point is there is no reason to heavily couple such functionality together.

**Comment by iampersistent** [comment]
I think what @merk is proposing here is a good way to approach it. It gives the chance to have a custom Product, Price or pricing service plus keeps things very loosely coupled.

**Comment by inspiran** [comment]
@merk  We could rename ProductView to ProductNode to make it more abstract. A node would contain multiple ProductNodeAttributes instances holding various product related information.

I also agree on the fact that updates to a ProductNode should be handled through individual services.

**Comment by inspiran** [comment]
closed
