### ISSUE TITLE
PHP Fatal error:  Class Doctrine\ORM\Mapping\ClassMetadataInfo contains 4 abstract methods and must therefore be declared abstract

### ISSUE THREAD

**Issue by akshayaptg** [vespolina/vespolina-sandbox#27]
While I am trying to execute the "php app/console doctrine:schema:create" command it shows the following error

PHP Fatal error:  Class Doctrine\ORM\Mapping\ClassMetadataInfo contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Doctrine\Common\Persistence\Mapping\ClassMetadata::getName, Doctrine\Common\Persistence\Mapping\ClassMetadata::getFieldNames, Doctrine\Common\Persistence\Mapping\ClassMetadata::getAssociationNames, ...) in /home/akshaya/code/rnd/vespolina/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php on line 1851
PHP Stack trace:
PHP   1. {main}() /home/akshaya/code/rnd/vespolina/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/akshaya/code/rnd/vespolina/app/console:16
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/akshaya/code/rnd/vespolina/vendor/symfony/src/Symfony/Component/Console/Application.php:118
PHP   4. Symfony\Component\Console\Application->doRun() /home/akshaya/code/rnd/vespolina/vendor/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:75
PHP   5. Symfony\Component\Console\Command\Command->run() /home/akshaya/code/rnd/vespolina/vendor/symfony/src/Symfony/Component/Console/Application.php:194
PHP   6. Symfony\Bundle\DoctrineBundle\Command\Proxy\CreateSchemaDoctrineCommand->execute() /home/akshaya/code/rnd/vespolina/vendor/symfony/src/Symfony/Component/Console/Command/Command.php:187
PHP   7. Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() /home/akshaya/code/rnd/vespolina/vendor/symfony/src/Symfony/Bundle/DoctrineBundle/Command/Proxy/CreateSchemaDoctrineCommand.php:59
PHP   8. Doctrine\ORM\Mapping\ClassMetadataFactory->getAllMetadata() /home/akshaya/code/rnd/vespolina/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:53
PHP   9. Doctrine\ORM\Mapping\ClassMetadataFactory->getMetadataFor() /home/akshaya/code/rnd/vespolina/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:124
PHP  10. Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() /home/akshaya/code/rnd/vespolina/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:170
PHP  11. Doctrine\ORM\Mapping\ClassMetadataFactory->newClassMetadataInstance() /home/akshaya/code/rnd/vespolina/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:261
PHP  12. Symfony\Component\ClassLoader\UniversalClassLoader->loadClass() /home/akshaya/code/rnd/vespolina/app/bootstrap.php.cache:0
PHP  13. require() /home/akshaya/code/rnd/vespolina/app/bootstrap.php.cache:2077
PHP  14. Symfony\Component\ClassLoader\UniversalClassLoader->loadClass() /home/akshaya/code/rnd/vespolina/app/bootstrap.php.cache:0
PHP  15. require() /home/akshaya/code/rnd/vespolina/app/bootstrap.php.cache:2077

**Comment by inspiran** [comment]
I'm not having this issue, -> closed
