### ISSUE TITLE
Following instructions with pear install gets error

### ISSUE THREAD

**Issue by cordoval** [vespolina/vespolina-sandbox#29]
cordoval@cordoval-G73Jw:~$ pear install -a ezc/eZComponents
PHP Fatal error:  Call to undefined method PEAR::raiseErro() in /usr/share/php/PEAR/REST.php on line 165
PHP Stack trace:
PHP   1. {main}() /usr/share/php/pearcmd.php:0
PHP   2. PEAR_Command_Common->run() /usr/share/php/pearcmd.php:305
PHP   3. PEAR_Command_Install->doInstall() /usr/share/php/PEAR/Command/Common.php:271
PHP   4. PEAR_Downloader->download() /usr/share/php/PEAR/Command/Install.php:661
PHP   5. PEAR_Downloader_Package->initialize() /usr/share/php/PEAR/Downloader.php:279
PHP   6. PEAR_Downloader_Package->_fromString() /usr/share/php/PEAR/Downloader/Package.php:190
PHP   7. PEAR_Downloader->_getPackageDownloadUrl() /usr/share/php/PEAR/Downloader/Package.php:1713
PHP   8. PEAR_REST_10->getDownloadURL() /usr/share/php/PEAR/Downloader.php:850
PHP   9. PEAR_REST->retrieveData() /usr/share/php/PEAR/REST/10.php:75

**Comment by inspiran** [comment]
This is not related to Vespolina but to your PEAR installation.  Check out http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=619307
