### ISSUE TITLE
Could not find any fixtures to load in

### ISSUE THREAD

**Issue by jekill** [vespolina/vespolina-sandbox#48]
Greetings! I try to install sandbox, but I can not find fixtures. 
Can somebody give me them?

```
  php app/console doctrine:mongodb:fixtures:load

  [InvalidArgumentException]
  Could not find any fixtures to load in:

  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\FrameworkBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\SecurityBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\TwigBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\MonologBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\SwiftmailerBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\DoctrineBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Symfony\Bundle\AsseticBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sensio\Bundle\FrameworkExtraBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\JMS\SecurityExtraBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\JMS\SerializerBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Symfony\Bundle\DoctrineFixturesBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Symfony\Bundle\DoctrineMongoDBBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sonata\EasyExtendsBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sonata\DoctrineORMAdminBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sonata\MediaBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sonata\AdminBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Knp\Bundle\MenuBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\FOS\RestBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\FOS\UserBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Mopa\BootstrapBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\app\Application\Sonata\MediaBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\src\Application\Vespolina\ProductBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\src\Application\UserBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\src\Application\DefaultBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\CoreBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\CustomerBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\ProductBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\PricingBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\OrderBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\FulfillmentBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\StoreBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Vespolina\MonetaryBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\JMS\DebuggingBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\src\Acme\DemoBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Behat\MinkBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Behat\BehatBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\symfony\src\Symfony\Bundle\WebProfilerBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sensio\Bundle\DistributionBundle/DataFixtures/MongoDB
  - C:\projects\WebSites\vespolina\vendor\bundles\Sensio\Bundle\GeneratorBundle/DataFixtures/MongoDB


doctrine:mongodb:fixtures:load [--fixtures[="..."]] [--append] [--dm="..."]
```

**Comment by inspiran** [comment]
Hey Jekill, sorry for the late reply (i didn't get any notification) but currently fixtures are loaded using the vespolina:setup command.  The objective is that fixtures will be loaded based on regional setttings .  Eg.  in Russia tax rules are different than in Belgium.   Hold on, we're working hard to fix the sandbox into an useful state.

**Comment by jekill** [comment]
Thanks!

**Comment by inspiran** [comment]
ps, i tried to private messaging you through github, but that doesn't work because you didn't set your email address on github.

**Comment by jekill** [comment]
You can send a message to me on  info@jeka.ru

**Comment by minokaze** [comment]
Hi, when i try to execute this command : 
php app/console doctrine:fixtures:load , 
I got this message 
[InvalidArgumentException]  
  Could not find any fixtures to load in:                                     
- /var/www/Symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBund  
  le/DataFixtures/ORM  
- /var/www/Symfony/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundl  
  e/DataFixtures/ORM  
- /var/www/Symfony/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Da  
  taFixtures/ORM  
- /var/www/Symfony/vendor/symfony/monolog-bundle/Symfony/Bundle/MonologBun  
  dle/DataFixtures/ORM  
- /var/www/Symfony/vendor/symfony/swiftmailer-bundle/Symfony/Bundle/Swiftm  
  ailerBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/symfony/assetic-bundle/Symfony/Bundle/AsseticBun  
  dle/DataFixtures/ORM  
- /var/www/Symfony/vendor/doctrine/doctrine-bundle/Doctrine/Bundle/Doctrin  
  eBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/sensio/framework-extra-bundle/Sensio/Bundle/Fram  
  eworkExtraBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/jms/aop-bundle/JMS/AopBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/jms/di-extra-bundle/JMS/DiExtraBundle/DataFixtur  
  es/ORM  
- /var/www/Symfony/vendor/jms/security-extra-bundle/JMS/SecurityExtraBundl  
  e/DataFixtures/ORM  
- /var/www/Symfony/src/Amine/BlogBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/doctrine/doctrine-fixtures-bundle/Doctrine/Bundl  
  e/FixturesBundle/DataFixtures/ORM  
- /var/www/Symfony/src/Acme/DemoBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBu  
  ndle/DataFixtures/ORM  
- /var/www/Symfony/vendor/sensio/distribution-bundle/Sensio/Bundle/Distrib  
  utionBundle/DataFixtures/ORM  
- /var/www/Symfony/vendor/sensio/generator-bundle/Sensio/Bundle/GeneratorB  
  undle/DataFixtures/ORM 

I don't know what to do , plz can anybody help me
