### ISSUE TITLE
Missing ProductController in StoreBundle

### ISSUE THREAD

**Issue by madc** [vespolina/vespolina-sandbox#62]
Product overview is working, but Product detail view and 'Buy'-Button will cause an error. Changing the route to the ProductBundle wont work either.

**Comment by inspiran** [comment]
Hey, i'm aware of this issue.  Normally by the end of the week I'll be pushing an update to the sandbox.

**Comment by madc** [comment]
Thanks for the info!
Is there anything I can do, to get my installation running or do i have to wait for this update?

**Comment by inspiran** [comment]
The missing files where added in the master

**Comment by madc** [comment]
Thanks!
