### ISSUE TITLE
Increase quantity instead of adding a second product to the cart.

### ISSUE THREAD

**Issue by madc** [vespolina/vespolina-sandbox#64]
When adding the same Product twice to the cart, the quantity should be increase. At the moment, a second position is added to the cart. Also the user has to be redirected to the cart after adding, otherwise a reload of the page adds another position to the cart.

**Comment by iampersistent** [comment]
Thanks, I'm working this and I'll have a fix in the CartBundle in a couple of days

**Comment by iampersistent** [comment]
Fixed with PR #66
