### ISSUE TITLE
corrupted composer packages

### ISSUE THREAD

**Issue by ghost** [vespolina/vespolina-sandbox#65]
following the installation steps, trying to install required packages via composer:

php composer.phar install
Installing from lock file

  [LogicException]  
  Can not find "doctrine/doctrine-workflow-dev-master" package in registered repositories

deleting the composer.lock and retry:

php composer.phar install
Installing dependencies
Your requirements could not be solved to an installable set of packages.

```
Problems:
    - Problem caused by:
        - Installation of package "mopa/bootstrap-bundle" with constraint == 9999999-dev was requested. Satisfiable by packages [mopa/bootstrap-bundle-9999999-dev].
        - Package "mopa/bootstrap-bundle-9999999-dev" contains the rule mopa/bootstrap-bundle requires twitter/bootstrap (== 9999999-dev). No package satisfies this dependency.
```

Setup of vespolin-sandbox failed

**Comment by inspiran** [comment]
Thx for reporting, the issue was fixed

**Comment by ghost** [comment]
There's still a little quirk:

Generating autoload files
PHP Fatal error:  Class 'Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle' not found in $/vespolina-sandbox/app/AppKernel.php on line 18

Fatal error: Class 'Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle' not found in $/vespolina-sandbox/app/AppKernel.php on line 18
PHP Fatal error:  Class 'Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle' not found in $/vespolina-sandbox/app/AppKernel.php on line 18

Fatal error: Class 'Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle' not found in $/vespolina-sandbox/app/AppKernel.php on line 18

running php composer.phar -v install

**Comment by ghost** [comment]
Maybe the namespace in file vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/MopaBootstrapBundle should be namespace Mopa\Bundle\BootstrapBundle rahter then namespace Mopa\BootstrapBundle;

Check also the Bundle-File MopaBootstrapBundle to correct the use-directive for Bundle and Compiler Pass-Class

**Comment by ghost** [comment]
for my local installation that fix works fine

**Comment by inspiran** [comment]
actually the  composer.lock was pointing to an "old" mopa bootstrap bundle.  I've updated that file and it is working now fine here: composer is now loading the latest bootstrap bundle
