### ISSUE TITLE
Probleme to install vespolina-sandbox

### ISSUE THREAD

**Issue by alainivars** [vespolina/vespolina-sandbox#72]
I have follow all the instruction in the page : https://github.com/vespolina/vespolina-sandbox/wiki/Getting-started
and in the page : https://github.com/vespolina/vespolina-sandbox

I'm on Ubuntu 12.04

Apache2, Mysql an mongodb run well

but when I run the command : php composer.phar install
I get the error message:
[InvalidArgumentException]  
  The file "store.xml" does not exist (in: /home/alain/repositories/vespolina-sandbox/vendor/vespolina/store-bundle/Vespolina/StoreBundle/DependencyInjection/../Resources/config).

And it's right the file don't exist and I can't find any documentation about this file should content

Help please, what is this file and what I made wrong ?

**Comment by inspiran** [comment]
Looks like i forgot to upload that file, will do it this evening.  thx for reporting

**Comment by alainivars** [comment]
I can't see it in :
https://github.com/vespolina/VespolinaStoreBundle/tree/master/Resources/config
To permit to me to try vespolina, can you first put the content of "store.xml" file in the answer on this message,
Regards,

**Comment by alainivars** [comment]
3 days waiting an answer and no file "store.xml" ...

**Comment by inspiran** [comment]
hey, sorry for the delay, I've been pretty busy setting up a new server.  Hold on for a moment, will do it this evening.

**Comment by inspiran** [comment]
fyi, the file was added.  More commits are coming :-)

**Comment by alainivars** [comment]
Thank, after copy the store.xml, I get the error:

An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 2 passed to Vespolina\CartBundle\Document\CartManager::__construct() must be an instance of Symfony\Component\HttpFoundation\Session, instance of Symfony\Component\HttpFoundation\Session\Session given, called in /home/alain/repositories/sf2_vespolina-sandbox/app/cache/dev/appDevDebugProjectContainer.php on line 3354 and defined in /home/alain/repositories/sf2_vespolina-sandbox/vendor/vespolina/cart-bundle/Vespolina/CartBundle/Document/CartManager.php line 31") in ::base.html.twig at line 29.

If I change the line 11 in CartManager.php
use Symfony\Component\HttpFoundation\Session;
by: use Symfony\Component\HttpFoundation\Session\Session;
to correct this error I get the error:
Method "isEmpty" for object "Application\Vespolina\CartBundle\Document\Cart" does not exist in VespolinaStoreBundle:Cart:quickInspection.html.twig at line 3 

Do you have an Idea ? :-)
My system is :
Linux beowolf007 3.2.0-24-generic-pae #38-Ubuntu SMP Tue May 1 16:40:26 UTC 2012 i686 i686 i386 GNU/Linux
Apache 2
PHP 5.3.10-1ubuntu3.1
Symfony 2.1.0

**Comment by inspiran** [comment]
Assure that vendor/vespolina/cart-bundle is pointing to the latest head as stated in the vespolina-sandbox/composer.lock.  
https://github.com/vespolina/VespolinaCartBundle

**Comment by alainivars** [comment]
Good, that start fine, Regards ;-)
