### ISSUE TITLE
di-extra-bundle compser problem

### ISSUE THREAD

**Issue by goof03** [vespolina/vespolina-sandbox#86]
Problem 1
    - Installation request for jms/di-extra-bundle == 1.1.9999999.9999999-dev -> satisfiable by jms/di-extra-bundle 1.1.x-dev.
    - Can only install one of: jms/di-extra-bundle dev-master, jms/di-extra-bundle 1.1.x-dev.
    - Installation request for jms/di-extra-bundle == 9999999-dev -> satisfiable by jms/di-extra-bundle dev-master.

What does this mean ? and what can i do please ?

**Comment by goof03** [comment]
ok php composer.phar update solve problem …

**Comment by inspiran** [comment]
Yeah, the problem was in cart bundle which i fixed some moments ago.  Thx for reporting anyhow.
